todo/urls.py
from django.urls import path

from todo.views import (
    TaskListView,
    TagListView,
    TagDetailView,
    TagUpdateView,
    TagDeleteView,
    TagCreateView,
    TaskCreateView,
    TaskDetailView,
    TaskUpdateView,
    TaskDeleteView,
    change_status,
)

urlpatterns = [
    path("", TaskListView.as_view(), name="task-list"),
    path("create/", TaskCreateView.as_view(), name="task-create"),
    path("<int:pk>/", TaskDetailView.as_view(), name="task-detail"),
    path("<int:pk>/update/", TaskUpdateView.as_view(), name="task-update"),
    path("<int:pk>/delete/", TaskDeleteView.as_view(), name="task-delete"),
    path("<int:pk>/change-status/", change_status, name="change-status"),
    path("tags/", TagListView.as_view(), name="tag-list"),
    path("tags/<int:pk>/", TagDetailView.as_view(), name="tag-detail"),
    path("tags/create/", TagCreateView.as_view(), name="tag-create"),
    path("tags/<int:pk>/update/", TagUpdateView.as_view(), name="tag-update"),
    path("tags/<int:pk>/delete/", TagDeleteView.as_view(), name="tag-delete")
]

app_name = "todo"

todo_list/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("todo.urls", namespace="todo"))
]

todo/models.py
from django.db import models


class Tag(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self) -> str:
        return self.name


class Task(models.Model):
    content = models.CharField(max_length=255)
    create = models.DateTimeField(auto_now_add=True)
    deadline = models.DateTimeField(blank=True, null=True)
    status = models.BooleanField(default=False)
    tags = models.ManyToManyField(Tag, related_name="tasks")

    class Meta:
        ordering = ("status", "-create")

    def __str__(self) -> str:
        return self.content

todo/views.py
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views import generic

from todo.models import Task, Tag


class TaskListView(generic.ListView):
    model = Task


class TaskDetailView(generic.DetailView):
    model = Task


class TaskCreateView(generic.CreateView):
    model = Task
    fields = "__all__"
    success_url = reverse_lazy("todo:task-list")


class TaskUpdateView(generic.UpdateView):
    model = Task
    fields = "__all__"
    success_url = reverse_lazy("todo:task-list")


class TaskDeleteView(generic.DeleteView):
    model = Task
    fields = "__all__"
    success_url = reverse_lazy("todo:task-list")


class TagListView(generic.ListView):
    model = Tag


class TagDetailView(generic.DetailView):
    model = Tag


class TagCreateView(generic.CreateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("todo:tag-list")


class TagUpdateView(generic.UpdateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("todo:tag-list")


class TagDeleteView(generic.DeleteView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("todo:tag-list")


def change_status(request, pk):
    task = Task.objects.get(id=request.user.id)
    if task.status:
        task.status = False
    else:
        task.status = True
    return redirect("todo:task-list", pk=pk)

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  {% block title %}<title>Todo List</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
      integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"
      crossorigin="anonymous">
  <!-- Add additional CSS in static file -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-2">

      {% block sidebar %}
        {% include "includes/sidebar.html" %}
      {% endblock %}

    </div>
    <div class="col-sm-10 ">

      {% block content %}{% endblock %}

    </div>
  </div>
</div>
</body>

</html>

templates/includes/sidebar.html
<ul class="sidebar-nav list-group">
  <li class="list-group-item" style="background-color: white"><a href="{% url 'todo:task-list' %}">Home</a></li>
  <li class="list-group-item" style="background-color: white"><a href="{% url 'todo:tag-list' %}">Tags</a></li>
</ul>

templates/todo/tag_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1 style="color: black">Delete tag</h1>
  <p>Are you sure you want to delete the tag {{ tag }}?</p>

  <form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Yes, delete" class="btn btn-danger">
    <a href="{% url 'todo:tag-list' %}" class="btn btn-secondary">No, I change my mind</a>
  </form>
{% endblock %}

templates/todo/tag_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1 style="color: black">{{ object|yesno:"Update,Create" }} Tag</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <input class="btn btn-primary" type="submit" value="Submit">
  </form>
{% endblock %}

templates/todo/tag_list.html
{% extends "base.html" %}

{% block content %}
    <h1 style="color: black">
      Tags
      <a href="{% url 'todo:tag-create' %}" class="btn btn-primary link-to-page" style="float: right">
        Add
      </a>
    </h1>

    {% if tag_list %}
    <table class="table">
      <tr>
        <th>Name</th>
        <th>Update</th>
        <th>Delete</th>
      </tr>
    {% for tag in tag_list %}
      <tr style="background-color: white">
        <td>{{ tag.name }}</td>
        <td><a href="{% url 'todo:tag-update' pk=tag.id %}" class="btn btn-secondary link-to-page">UPDATE</a></td>
        <td><a href="{% url 'todo:tag-delete' pk=tag.id %}" class="btn btn-secondary link-to-page">DELETE</a></td>
      </tr>
    {% endfor %}

    </table>
    {% else %}
      <p>There are no tags!</p>
    {% endif %}
{% endblock %}

templates/todo/task_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1 style="color: black">Delete task</h1>
  <p>Are you sure you want to delete the tag {{ tag }}?</p>

  <form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Yes, delete" class="btn btn-danger">
    <a href="{% url 'todo:task-list' %}" class="btn btn-secondary">No, I change my mind</a>
  </form>
{% endblock %}

templates/todo/task_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1 style="color: black">{{ object|yesno:"Update,Create" }} task</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <input class="btn btn-primary" type="submit" value="Submit">
  </form>
{% endblock %}

templates/todo/task_list.html
{% extends "base.html" %}

{% block content %}
  <h1 style="color: black">
    TODO list
    <a href="{% url 'todo:task-create' %}" class="btn btn-primary link-to-page" style="float: right">
      Add task
    </a>
  </h1>
  {% if task_list %}
    {% for task in task_list %}
      <p>
        <strong>{{ task.content }}</strong>
        {% if task.status %}
          <a href="{% url 'todo:change-status' pk=task.id %}" class="btn btn-secondary" style="float: right">
            Undo
          </a>
        {% else %}
          <a href="{% url 'todo:change-status' pk=task.id %}" class="btn btn-success" style="float: right">
            Complete
          </a>
        {% endif %}
        {% if task.status %}
          <strong style="color: green">Done</strong>
        {% else %}
          <strong style="color: red">Not done</strong>
        {% endif %}
      </p>
      <p>
        Created: {{ task.create }}
        {% if task.deadline %}
          Deadline: {{ task.deadline }}
        {% endif %}
      </p>
      <p>
        Tags:
        {% for tag in task.tags.all %}
          {{ tag.name }}
        {% endfor %}

        <a href="{% url 'todo:task-update' pk=task.id %}">Update</a>
        <a href="{% url 'todo:task-delete' pk=task.id %}">Delete</a>
      </p>
      <hr>

    {% endfor %}
  {% else %}
    <p>There are no tasks!</p>
  {% endif %}
{% endblock %}